# Generated by Django 5.2.6 on 2025-12-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaint_App', '0002_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
